/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.ClienteControlador;
import Modelo.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author COMPHP
 */
public class VistaClientes extends javax.swing.JPanel {
    private final ClienteControlador clienteControlador;
    private Integer idClienteSeleccionado = null;
    /**
     * Creates new form VistaClientes
     */
    public VistaClientes() {
        initComponents();
        this.clienteControlador = new ClienteControlador();
        cargarDatosTabla();
    }
    
     public void cargarDatosTabla() {
        //Obtener todas las categorias del controlador
        List<Cliente> clientes = clienteControlador.obtenerTodosClientes();
        if (clientes != null) {
            // obtener el modelo existente de la tabla
            DefaultTableModel model = (DefaultTableModel) tablaCliente.getModel();
            model.setRowCount(0);
            //llenar las filas con los datos de categorias  
            for (Cliente cli : clientes) {
                Object[] row = {
                    cli.getIdCliente(),
                    cli.getNombre_1(),
                    cli.getApellido_1(),
                    cli.getDirrecion_cliente(),
                    cli.getTelefono_cliente()
                };
                model.addRow(row);
            }
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        textnombre_1 = new javax.swing.JTextField();
        textapellido_1 = new javax.swing.JTextField();
        textdireccion_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        texttelefono_cliente = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        textBuscarCliente = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jlabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 255, 255));
        jlabel1.setText("nombre_1");

        jlabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel2.setText("apellido_1");

        textnombre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnombre_1ActionPerformed(evt);
            }
        });

        textapellido_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textapellido_1ActionPerformed(evt);
            }
        });

        textdireccion_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdireccion_clienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("direccion_cliente");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("telefono_cliente");

        texttelefono_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttelefono_clienteActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionbtnGuardar(evt);
            }
        });

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionbtnActualizar(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionbtnbtnEliminar(evt);
            }
        });

        textBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscarClienteActionPerformed(evt);
            }
        });
        textBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarClienteKeyTyped(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idCliente", "nombre_1", "apellido_1", "direccion_cliente", "telefono_cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(textBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jlabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(textnombre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jlabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(textapellido_1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(106, 106, 106)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(textdireccion_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(107, 107, 107)
                                                .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(texttelefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 278, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textnombre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textapellido_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textdireccion_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texttelefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textnombre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnombre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnombre_1ActionPerformed

    private void textapellido_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textapellido_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textapellido_1ActionPerformed

    private void textdireccion_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdireccion_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdireccion_clienteActionPerformed

    private void texttelefono_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttelefono_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttelefono_clienteActionPerformed

    private void accionbtnGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionbtnGuardar
        String nombre_1 = textnombre_1.getText();
        String apellido_1 = textapellido_1.getText();
        String direccion_cliente = textdireccion_cliente.getText();
        String telefono_cliente = texttelefono_cliente.getText();
        
        if (!nombre_1.isEmpty() && !apellido_1.isEmpty() && !direccion_cliente.isEmpty() && !telefono_cliente.isEmpty()) {
            clienteControlador.crearCliente(nombre_1,apellido_1, direccion_cliente,telefono_cliente);
            cargarDatosTabla();
            textnombre_1.setText("");
            textapellido_1.setText("");
            textdireccion_cliente.setText("");
            texttelefono_cliente.setText("");
        } else {            
            javax.swing.JOptionPane.showMessageDialog(this, "por favor, llene todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionbtnGuardar

    private void accionbtnActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionbtnActualizar
       String nombre_1 = textnombre_1.getText();
        String apellido_1 = textapellido_1.getText();
        String direccion_cliente = textdireccion_cliente.getText();
        String telefono_cliente = texttelefono_cliente.getText();
        if (idClienteSeleccionado != null && !nombre_1.isEmpty() && !apellido_1.isEmpty() && !direccion_cliente.isEmpty() && !telefono_cliente.isEmpty()){
            clienteControlador.actualizarCliente(idClienteSeleccionado, nombre_1,apellido_1, direccion_cliente, telefono_cliente);
            cargarDatosTabla();
            
            textnombre_1.setText("");
            textapellido_1.setText("");
            textdireccion_cliente.setText("");
            texttelefono_cliente.setText("");
            idClienteSeleccionado = null;
            
            btnEliminar.setEnabled(true);
            btnGuardar.setEnabled(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "por favor, llene todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE); 
        }
                      
    }//GEN-LAST:event_accionbtnActualizar

    private void accionbtnbtnEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionbtnbtnEliminar
        int filaSelecionada = tablaCliente.getSelectedRow();
        if (filaSelecionada != -1) {
            int idCliente = (int) tablaCliente.getValueAt(filaSelecionada, 0);
            clienteControlador.eliminarCliente(idCliente);
            cargarDatosTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionbtnbtnEliminar

    private void textBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscarClienteActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        if (evt.getClickCount() == 2) {
            
            int filaSelecionada = tablaCliente.getSelectedRow();
            
            if (filaSelecionada != -1) {
                idClienteSeleccionado = (int) tablaCliente.getValueAt(filaSelecionada, 0);
                String nombre_1 = (String) tablaCliente.getValueAt(filaSelecionada, 1);
                String apellido_1 = (String) tablaCliente.getValueAt(filaSelecionada, 2);
                String direccion_cliente = (String) tablaCliente.getValueAt(filaSelecionada, 3);
                String telefono_cliente = (String) tablaCliente.getValueAt(filaSelecionada, 4);

                
                textnombre_1.setText(nombre_1);
                textapellido_1.setText(apellido_1);
                textdireccion_cliente.setText(direccion_cliente);
                texttelefono_cliente.setText(telefono_cliente);
                
                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void textBuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarClienteKeyTyped
         String textoBusqueda = textBuscarCliente.getText().trim().toLowerCase();
    List<Cliente> clientes = clienteControlador.obtenerTodosClientes();

    DefaultTableModel modelo = (DefaultTableModel) tablaCliente.getModel();
    modelo.setRowCount(0);

    if (clientes != null) {
        for (Cliente cli : clientes) {
            if (textoBusqueda.isEmpty() || 
                cli.getNombre_1().toLowerCase().contains(textoBusqueda) ||
                cli.getApellido_1().toLowerCase().contains(textoBusqueda) || 
                cli.getDirrecion_cliente().toLowerCase().contains(textoBusqueda) ||
                cli.getTelefono_cliente().toLowerCase().contains(textoBusqueda)) { 
                Object[] fila = {
                    cli.getIdCliente(),
                    cli.getNombre_1(),
                    cli.getApellido_1(),
                    cli.getDirrecion_cliente(),
                    cli.getTelefono_cliente()
                };
                modelo.addRow(fila);
            }
        }
    }
    }//GEN-LAST:event_textBuscarClienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField textBuscarCliente;
    private javax.swing.JTextField textapellido_1;
    private javax.swing.JTextField textdireccion_cliente;
    private javax.swing.JTextField textnombre_1;
    private javax.swing.JTextField texttelefono_cliente;
    // End of variables declaration//GEN-END:variables
}
