/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ProductoControlador;
import Controlador.CategoriaControlador;
import Modelo.Producto;
import Modelo.Categoria;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author COMPHP
 */
public class VistaProductos extends javax.swing.JPanel {

    private final ProductoControlador productoControlador;
    private Integer id_productoSeleccionado = null;
    private final CategoriaControlador categoriaControlador;
    private Integer idCategoriaSeleccionada = null;

    /**
     * Creates new form VistaProductos
     */
    public VistaProductos() {
        initComponents();
        this.productoControlador = new ProductoControlador();
        this.categoriaControlador = new CategoriaControlador();
        cargarDatosTabla();
        cargarCategorias();
    }

    private void limpiar() {
        textnombre_producto.setText("");
        textprecio_costo.setText("");
        textprecio_venta.setText("");
        textexistencia.setText("");
        textBuscarProducto.setText("");
        id_productoSeleccionado = null;
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(true);
    }

    public void cargarDatosTabla() {
        //Obtener todas las categorias del controlador
        List<Producto> productos = productoControlador.obtenerTodosProductos();
        if (productos != null) {
            // obtener el modelo existente de la tabla
            DefaultTableModel model = (DefaultTableModel) tablaProducto.getModel();
            model.setRowCount(0);
            //llenar las filas con los datos de categorias  
            for (Producto prod : productos) {
                Object[] row = {
                    prod.getId_producto(),
                    prod.getNombre_producto(),
                    prod.getPrecio_costo(),
                    prod.getPrecio_venta(),
                    prod.getExistencia(),
                    prod.getId_categoria()
                };
                model.addRow(row);
            }
        }
    }
    private void cargarCategorias() {
        try {
// Obtener las categorías desde el controlador
            List<Categoria> categorias
                    = categoriaControlador.obtenerTodasCategorias();
// Limpiar el combo box por si tiene datos
            comboCategoria.removeAllItems();
// Agregar cada categoría al combo box
            for (Categoria cat : categorias) {
                comboCategoria.addItem(cat.getNombre_categoria());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar las categorías: " + e.getMessage());
        }
    }
      private void eventoComboCategorias() {
    comboCategoria.addActionListener(e -> {
        // Obtener el índice seleccionado
        int indiceSeleccionado = comboCategoria.getSelectedIndex();

        if (indiceSeleccionado >= 0) { // Verificar que se haya seleccionado algo
            try {
                // Obtener la lista de categorías desde el controlador o memoria
                List<Categoria> categorias = categoriaControlador.obtenerTodasCategorias();

                // Obtener el objeto de categoría correspondiente al índice seleccionado
                Categoria categoriaSeleccionada = categorias.get(indiceSeleccionado);

                // Actualizar la variable global con el ID de la categoría seleccionada
                idCategoriaSeleccionada = categoriaSeleccionada.getId_categoria();

                // Mostrar el ID seleccionado en la consola (puedes quitar esta línea)
                System.out.println("ID de la categoría seleccionada: " + idCategoriaSeleccionada);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al seleccionar categoría: " + ex.getMessage());
            }
        }
    });
  }
      private void seleccionarCategoriaEnCombo(Integer idCategoria) {
    try {
        // Obtener las categorías desde el controlador
        List<Categoria> categorias = categoriaControlador.obtenerTodasCategorias();

        // Recorrer las categorías y buscar la que coincida con el ID
        for (int i = 0; i < categorias.size(); i++) {
            Categoria categoria = categorias.get(i);
            if (categoria.getId_categoria()== idCategoria) {
                comboCategoria.setSelectedIndex(i);
                break;
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al seleccionar categoría: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        textnombre_producto = new javax.swing.JTextField();
        jlabel2 = new javax.swing.JLabel();
        textprecio_costo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textprecio_venta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textexistencia = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        textBuscarProducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jlabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 255, 255));
        jlabel1.setText("nombre_producto");

        textnombre_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnombre_productoActionPerformed(evt);
            }
        });

        jlabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel2.setText("precio_costo");

        textprecio_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprecio_costoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("precio_venta");

        textprecio_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprecio_ventaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("existencia");

        textexistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textexistenciaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionbtnGuardar(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionbtnEliminar(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        textBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscarProductoActionPerformed(evt);
            }
        });
        textBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarProductoKeyTyped(evt);
            }
        });

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_producto", "nombre_producto", "precio_costo", "precio_venta", "existencia", "Categorias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseCliked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProducto);

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionbtnLimpiarProducto(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoComboCategoria(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(textprecio_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(textnombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(109, 109, 109)
                                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(textprecio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(110, 110, 110)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(textBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)))
                        .addGap(0, 230, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textnombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textprecio_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textprecio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(textBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textnombre_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnombre_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnombre_productoActionPerformed

    private void textprecio_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprecio_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprecio_costoActionPerformed

    private void textprecio_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprecio_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprecio_ventaActionPerformed

    private void textexistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textexistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textexistenciaActionPerformed

    private void accionbtnGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionbtnGuardar
        String nombre_producto = textnombre_producto.getText();
        String precio_costoStr = textprecio_costo.getText();
        String precio_ventaStr = textprecio_venta.getText();
        String existenciaStr = textexistencia.getText();
        int id_categoria = idCategoriaSeleccionada;

        if (!nombre_producto.isEmpty() && !precio_costoStr.isEmpty() && !precio_ventaStr.isEmpty() && !existenciaStr.isEmpty()) {
            
                float precio_costo = Float.parseFloat(precio_costoStr.trim().replace(",", "."));
                float precio_venta = Float.parseFloat(precio_ventaStr.trim().replace(",", "."));
                int existencia = Integer.parseInt(existenciaStr.trim());
                try {
                
                productoControlador.crearProducto(
                nombre_producto,
                precio_costo,
               precio_venta,
               existencia,
               id_categoria);     
               limpiar();
            cargarDatosTabla();
            cargarCategorias();

           } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error en los datos: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Por favor, llene todos los campos obligatorios correctamente.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_accionbtnGuardar

    private void accionbtnEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionbtnEliminar
        int filaSeleccionada = tablaProducto.getSelectedRow();
    if (filaSeleccionada != -1) {
        int idProducto = (int) tablaProducto.getValueAt(filaSeleccionada, 0);
        productoControlador.eliminarProducto(idProducto);
        cargarDatosTabla();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Selecciona una fila para eliminar.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_accionbtnEliminar

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // Obtenemos los valores de los campos de texto
        String nombre_producto = textnombre_producto.getText();
        float precio_costo = Float.parseFloat(textprecio_costo.getText());
        float precio_venta = Float.parseFloat(textprecio_venta.getText());
        int existencia = Integer.parseInt(textexistencia.getText());
        int id_categoria = idCategoriaSeleccionada;
        

// Verificamos que todos los campos estén llenos y el id del producto esté seleccionado
        if (id_productoSeleccionado != null 
                && !nombre_producto.isEmpty()
                && id_categoria >= 0) {
          
                try {
                // Llamamos al controlador para actualizar el producto
                productoControlador.actualizarProducto(id_productoSeleccionado,
                     nombre_producto, precio_costo, precio_venta, existencia,id_categoria);

                
               cargarDatosTabla(); // Vuelve a cargar los datos en la tabla después de actualizar
            limpiar(); // Limpia los campos
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error en los datos: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Por favor, llene todos los campos obligatorios.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaProductosMouseCliked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseCliked
        if (evt.getClickCount() == 2) {
            int filaSelecionada = tablaProducto.getSelectedRow();

            if (filaSelecionada != -1) {
                id_productoSeleccionado = (Integer) tablaProducto.getValueAt(filaSelecionada, 0);
                String nombre_producto = (String) tablaProducto.getValueAt(filaSelecionada, 1);
                Float precio_costo = (Float) tablaProducto.getValueAt(filaSelecionada, 2);
                Float precio_venta = (Float) tablaProducto.getValueAt(filaSelecionada, 3);
                Integer existencia = (Integer) tablaProducto.getValueAt(filaSelecionada, 4);
                Integer id_categoria = (Integer) tablaProducto.getValueAt(filaSelecionada, 5);

                textnombre_producto.setText(nombre_producto);
                textprecio_costo.setText(String.valueOf(precio_costo));
                textprecio_venta.setText(String.valueOf(precio_venta));
                textexistencia.setText(String.valueOf(existencia));
                
                // Seleccionar la categoría correspondiente en el combo
            seleccionarCategoriaEnCombo(id_categoria);
            idCategoriaSeleccionada = id_categoria;
            
                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tablaProductosMouseCliked

    private void textBuscarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarProductoKeyTyped
        String textoBusqueda = textBuscarProducto.getText().trim().toLowerCase();
        List<Producto> productos = productoControlador.obtenerTodosProductos();

        DefaultTableModel modelo = (DefaultTableModel) tablaProducto.getModel();
        modelo.setRowCount(0);
        if (productos != null) {
            for (Producto prod : productos) {
                try {
                    String nombre_producto = prod.getNombre_producto().toLowerCase();
                    String precio_costo = String.valueOf(prod.getPrecio_costo()).toLowerCase();
                    String precio_venta = String.valueOf(prod.getPrecio_venta()).toLowerCase();
                    String existencia = String.valueOf(prod.getExistencia()).toLowerCase();

                    if (textoBusqueda.isEmpty()
                            || nombre_producto.contains(textoBusqueda)
                            || precio_costo.contains(textoBusqueda)
                            || precio_venta.contains(textoBusqueda)
                            || existencia.contains(textoBusqueda)) {

                        Object[] fila = {
                            prod.getId_producto(),
                            prod.getNombre_producto(),
                            prod.getPrecio_costo(),
                            prod.getPrecio_venta(),
                            prod.getExistencia()
                        };
                        modelo.addRow(fila);
                    }
                } catch (NullPointerException e) {
                    System.out.println("Error al procesar el producto: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_textBuscarProductoKeyTyped

    private void textBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscarProductoActionPerformed

    private void AccionbtnLimpiarProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionbtnLimpiarProducto
        // TODO add your handling code here:
        textnombre_producto.setText("");
        textprecio_costo.setText("");
        textprecio_venta.setText("");
        textexistencia.setText("");
        textBuscarProducto.setText("");
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_AccionbtnLimpiarProducto

    private void eventoComboCategoria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoComboCategoria
        // TODO add your handling code here:
        // TODO add your handling code here:
        comboCategoria.addActionListener(e -> {
        // Obtener el índice seleccionado
        int indiceSeleccionado = comboCategoria.getSelectedIndex();

        if (indiceSeleccionado >= 0) { // Verificar que se haya seleccionado algo
            try {
                // Obtener la lista de categorías desde el controlador o memoria
                List<Categoria> categorias = categoriaControlador.obtenerTodasCategorias();

                // Obtener el objeto de categoría correspondiente al índice seleccionado
                Categoria categoriaSeleccionada = categorias.get(indiceSeleccionado);

                // Actualizar la variable global con el ID de la categoría seleccionada
                idCategoriaSeleccionada = categoriaSeleccionada.getId_categoria();

                // Mostrar el ID seleccionado en la consola (puedes quitar esta línea)
                System.out.println("ID de la categoría seleccionada: " + idCategoriaSeleccionada);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al seleccionar categoría: " + ex.getMessage());
            }
        }
    });
    }//GEN-LAST:event_eventoComboCategoria

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextField textBuscarProducto;
    private javax.swing.JTextField textexistencia;
    private javax.swing.JTextField textnombre_producto;
    private javax.swing.JTextField textprecio_costo;
    private javax.swing.JTextField textprecio_venta;
    // End of variables declaration//GEN-END:variables
}
